[package]
name = "ghwt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
dirs-next = "2.0.0"
toml = "0.9.2"
toml_edit = "0.23.1"
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
tempfile = "3.20.0"
