# rustfmt.toml
# Use defaults for most things
version = "Two" # Specifies the version of rustfmt rules to use. "Two" is the latest.
max_width = 100 # Maximum line width
use_small_heuristics = "Max" # More aggressively formats lines to fit within max_width
reorder_imports = true # Reorder import statements alphabetically
reorder_modules = true # Reorder module statements alphabetically
remove_nested_parens = true # Remove nested parentheses where possible
short_array_element_width_threshold = 10 # Threshold for deciding to put array elements on new lines
struct_lit_width = 60 # Width threshold for struct literals before breaking to multiple lines
fn_call_width = 60 # Width threshold for function calls before breaking to multiple lines
# For more options: https://rust-lang.github.io/rustfmt/
